<?php
	$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/preferences.js');
?><div class="container">

	<section id="about" >
		<div class="purpose cardColorOverlay">
			<div class="version">
				v0.9
			</div>
		<h2>Food is best at its peak.</h2>
		<p>Peakfoods is a free resource for anyone wanting to think and eat more like a chef. There's good reason many of the top restaurants in the world are known for their seasonal menus; besides just tasting better, seasonal foods:</p>
		<ul>
			<li>Have higher vitamin and nutrient retention</li>
			<li>Cost less as they don’t need to be packed and shipped long distances</li>
			<li>Reduce fossil-fuel usage and carbon emissions</li>
			<li>Better support your local economy and local farming</li>
			<li>Require little to no processing or chemicals to preserve freshness</li>
		</ul>
		<p>We're working hard on adding some features we think you will love. Stay tuned!</p>
		<div class="social">
			<a href="https://twitter.com/share" class="twitter-share-button" data-lang="en" data-url="http://peakfoods.org" data-text="Check out @Peakfoods - food is best at its peak. ">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
<div class="fb-like" data-href="http://www.peakfoods.org" data-send="true" data-width="450" data-show-faces="true" data-font="segoe ui"></div>
		</div>
	</div>
	<div class="origin cardColorOverlay">
		<h2>Origin</h2>
		<p>Peakfoods was created as an experiment through <a href="http://hidef.co" target="_blank">HiDef, Inc.’s</a> innovative <a href="http://www.hidef.co/services-process/causelabs/" target="_blank">CauseLabs program</a>, a platform for self-organized teams to work on new ideas that have potential for positive impact. </p>
		<a href="http://www.hidef.co/services-process/causelabs/" target="_blank"><img src="<?php echo BASEURL ?>img/layout/causelabs.png"></a>
	</div>
	<div class="team cardColorOverlay">
		<h2>Team</h2>
		<ul id="members">
			<li class="member">
				<img src="<?php echo BASEURL ?>img/layout/pete.jpg">
				<span class="member-name">Pete Petrash</span>
				<span class="member-role">Design & Development</span>
				<a class="twitter" href="http://twitter.com/petepetrash">@petepetrash</a>
			</li>

			<li class="member">
				<img src="<?php echo BASEURL ?>img/layout/rick.jpg">
				<span class="member-name">Rick Sharp</span>
				<span class="member-role">Engineering & Development</span>
			</li>
		</ul>
	</div>
	</section>
	<!-- //about -->

</div>
<!-- //container -->

